# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Hai Hu
tagline:          'love for language'
description:      'PhD student in linguistics'
url:              https://huhailinguist.github.io
baseurl:          ''

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5
gems:             [jekyll-gist]

# Custom vars
version:          1.0

github:
  repo:           https://github.com/huhailinguist/
  
# Google Analytics
google_analytics: UA-163396355-1
